### ISSUE TITLE
TypeError: Cannot convert a Symbol value to a string at Array.join (native)

### ISSUE THREAD

**Issue by darwin** [binaryage/cljs-devtools#25]
## This is a re-post of https://github.com/binaryage/dirac/issues/34

Hi,

Encountered the error when browsing through stacks at a break point. Below is the stack trace from that error. Chrome didn't output source map line numbers for a few frames at the bottom, not sure this stack trace are helpful or not.

```
core.cljs:65 CLJS DevTools internal error: TypeError: Cannot convert a Symbol value to a string
    at Array.join (native)
    at Function.cljs.core.str.cljs$core$IFn$_invoke$arity$1 (http://localhost:3450/js/compiled/test_out/cljs/core.js:9780:12)
    at Object.cljs$core$str [as str] (http://localhost:3450/js/compiled/test_out/cljs/core.js:9762:22)
    at cljs$core$pr_writer_impl (http://localhost:3450/js/compiled/test_out/cljs/core.js:31145:128)
    at devtools$formatters$printing$alt_printer_job (http://localhost:3450/js/compiled/test_out/devtools/formatters/printing.js:233:21)
    at devtools$formatters$printing$alt_printer_impl (http://localhost:3450/js/compiled/test_out/devtools/formatters/printing.js:248:46)
    at cljs$core$pr_writer (http://localhost:3450/js/compiled/test_out/cljs/core.js:31172:128)
    at http://localhost:3450/js/compiled/test_out/cljs/core.js:31613:131
    at Object.cljs$core$pr_sequential_writer [as pr_sequential_writer] (http://localhost:3450/js/compiled/test_out/cljs/core.js:30903:142)
    at cljs$core$print_map (http://localhost:3450/js/compiled/test_out/cljs/core.js:31602:18)
    at cljs$core$pr_writer_impl (http://localhost:3450/js/compiled/test_out/cljs/core.js:31092:170)
    at devtools$formatters$printing$alt_printer_job (http://localhost:3450/js/compiled/test_out/devtools/formatters/printing.js:233:21)
    at devtools$formatters$printing$alt_printer_impl (http://localhost:3450/js/compiled/test_out/devtools/formatters/printing.js:248:46)
    at cljs$core$pr_writer (http://localhost:3450/js/compiled/test_out/cljs/core.js:31172:128)
    at Object.cljs$core$pr_sequential_writer [as pr_sequential_writer] (http://localhost:3450/js/compiled/test_out/cljs/core.js:30903:142)
    at cljs.core.PersistentVector.cljs$core$IPrintWithWriter$_pr_writer$arity$3 (http://localhost:3450/js/compiled/test_out/cljs/core.js:31791:18)
    at cljs$core$pr_writer_impl (http://localhost:3450/js/compiled/test_out/cljs/core.js:31078:12)
    at devtools$formatters$printing$alt_printer_job (http://localhost:3450/js/compiled/test_out/devtools/formatters/printing.js:233:21)
    at devtools$formatters$printing$alt_printer_impl (http://localhost:3450/js/compiled/test_out/devtools/formatters/printing.js:248:46)
    at Object.cljs$core$pr_writer [as pr_writer] (http://localhost:3450/js/compiled/test_out/cljs/core.js:31172:128)
    at cljs$core$pr_seq_writer (http://localhost:3450/js/compiled/test_out/cljs/core.js:31178:11)
    at http://localhost:3450/js/compiled/test_out/devtools/formatters/printing.js:283:32
    at http://localhost:3450/js/compiled/test_out/devtools/formatters/printing.js:258:16
    at devtools$formatters$printing$managed_print (http://localhost:3450/js/compiled/test_out/devtools/formatters/printing.js:276:8)
    at devtools$formatters$printing$managed_print_via_writer (http://localhost:3450/js/compiled/test_out/devtools/formatters/printing.js:282:51)
    at http://localhost:3450/js/compiled/test_out/devtools/formatters/markup.js:34:15
    at Function.devtools.formatters.markup.print_with.cljs$core$IFn$_invoke$arity$variadic (http://localhost:3450/js/compiled/test_out/devtools/formatters/markup.js:41:19)
    at devtools$formatters$markup$print_with (http://localhost:3450/js/compiled/test_out/devtools/formatters/markup.js:26:46)
    at Function.devtools.formatters.markup.print_via_writer.cljs$core$IFn$_invoke$arity$variadic (http://localhost:3450/js/compiled/test_out/devtools/formatters/markup.js:83:46)
    at devtools$formatters$markup$print_via_writer (http://localhost:3450/js/compiled/test_out/devtools/formatters/markup.js:77:52)
    at devtools$formatters$markup$_LT_preview_GT_ (http://localhost:3450/js/compiled/test_out/devtools/formatters/markup.js:400:52)
    at devtools$formatters$markup$_LT_header_GT_ (http://localhost:3450/js/compiled/test_out/devtools/formatters/markup.js:1054:106)
    at devtools$formatters$core$header_STAR_ (http://localhost:3450/js/compiled/test_out/devtools/formatters/core.js:56:149)
    at devtools.formatters.core.config_wrapper (http://localhost:3450/js/compiled/test_out/devtools/formatters/core.js:156:19)
    at Function.handler (http://localhost:3450/js/compiled/test_out/devtools/formatters/core.js:209:120)
    at Function.cljs.core.apply.cljs$core$IFn$_invoke$arity$2 (http://localhost:3450/js/compiled/test_out/cljs/core.js:12983:10)
    at cljs$core$apply (http://localhost:3450/js/compiled/test_out/cljs/core.js:12951:24)
    at devtools.formatters.CLJSDevtoolsFormatter.G__54238__delegate (http://localhost:3450/js/compiled/test_out/devtools/formatters/core.js:167:28)
    at devtools.formatters.CLJSDevtoolsFormatter.G__54238 [as header] (http://localhost:3450/js/compiled/test_out/devtools/formatters/core.js:180:27)
    at InjectedScript.RemoteObject._customPreview (<anonymous>:147:82)
    at InjectedScript.RemoteObject (<anonymous>:139:73)
    at InjectedScript._wrapObject (<anonymous>:43:13)
    at InjectedScript.getProperties (<anonymous>:51:23)
    at Function.<anonymous> (http://localhost:3450/js/compiled/test_out/webapp/react.js?zx=d29fd3515wqx:75:9)
    at Function.cljs.core.apply.cljs$core$IFn$_invoke$arity$3 (http://localhost:3450/js/compiled/test_out/cljs/core.js:12998:10)
    at cljs$core$apply (http://localhost:3450/js/compiled/test_out/cljs/core.js:12955:24)
    at render (http://localhost:3450/js/compiled/test_out/rum/core.js:209:107)
    at http://localhost:3450/js/compiled/test_out/react/util.js:219:33
    at Constructor.render (http://localhost:3450/js/compiled/test_out/rum/core.js:76:33)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:3450/js/compiled/test_out/lib.js:20139:34)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:3450/js/compiled/test_out/lib.js:20166:34)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:3450/js/compiled/test_out/lib.js:19703:30)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:3450/js/compiled/test_out/lib.js:19591:21)
    at Object.mountComponent (http://localhost:3450/js/compiled/test_out/lib.js:27270:35)
    at ReactDOMComponent.mountChildren (http://localhost:3450/js/compiled/test_out/lib.js:26012:44)
    at ReactDOMComponent._createInitialChildren (http://localhost:3450/js/compiled/test_out/lib.js:21122:32)
    at ReactDOMComponent.mountComponent (http://localhost:3450/js/compiled/test_out/lib.js:20947:12)
    at Object.mountComponent (http://localhost:3450/js/compiled/test_out/lib.js:27270:35)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:3450/js/compiled/test_out/lib.js:19716:34)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:3450/js/compiled/test_out/lib.js:19591:21)
    at Object.mountComponent (http://localhost:3450/js/compiled/test_out/lib.js:27270:35)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:3450/js/compiled/test_out/lib.js:19716:34)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:3450/js/compiled/test_out/lib.js:19591:21)
    at Object.mountComponent (http://localhost:3450/js/compiled/test_out/lib.js:27270:35)
    at ReactDOMComponent.mountChildren (http://localhost:3450/js/compiled/test_out/lib.js:26012:44)
    at ReactDOMComponent._createInitialChildren (http://localhost:3450/js/compiled/test_out/lib.js:21122:32)
    at ReactDOMComponent.mountComponent (http://localhost:3450/js/compiled/test_out/lib.js:20947:12)
    at Object.mountComponent (http://localhost:3450/js/compiled/test_out/lib.js:27270:35)
    at ReactDOMComponent.mountChildren (http://localhost:3450/js/compiled/test_out/lib.js:26012:44)
    at ReactDOMComponent._createInitialChildren (http://localhost:3450/js/compiled/test_out/lib.js:21122:32)
    at ReactDOMComponent.mountComponent (http://localhost:3450/js/compiled/test_out/lib.js:20947:12)
    at Object.mountComponent (http://localhost:3450/js/compiled/test_out/lib.js:27270:35)
    at ReactDOMComponent.mountChildren (http://localhost:3450/js/compiled/test_out/lib.js:26012:44)
    at ReactDOMComponent._createInitialChildren (http://localhost:3450/js/compiled/test_out/lib.js:21122:32)
    at ReactDOMComponent.mountComponent (http://localhost:3450/js/compiled/test_out/lib.js:20947:12)
    at Object.mountComponent (http://localhost:3450/js/compiled/test_out/lib.js:27270:35)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:3450/js/compiled/test_out/lib.js:19716:34)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:3450/js/compiled/test_out/lib.js:19591:21)
    at Object.mountComponent (http://localhost:3450/js/compiled/test_out/lib.js:27270:35)
    at ReactDOMComponent.mountChildren (http://localhost:3450/js/compiled/test_out/lib.js:26012:44)
    at ReactDOMComponent._createInitialChildren (http://localhost:3450/js/compiled/test_out/lib.js:21122:32)
    at ReactDOMComponent.mountComponent (http://localhost:3450/js/compiled/test_out/lib.js:20947:12)
    at Object.mountComponent (http://localhost:3450/js/compiled/test_out/lib.js:27270:35)
    at Object.updateChildren (http://localhost:3450/js/compiled/test_out/lib.js:17767:51)
    at ReactDOMComponent._reconcilerUpdateChildren (http://localhost:3450/js/compiled/test_out/lib.js:25982:32)
    at ReactDOMComponent._updateChildren (http://localhost:3450/js/compiled/test_out/lib.js:26086:31)
    at ReactDOMComponent.updateChildren (http://localhost:3450/js/compiled/test_out/lib.js:26073:12)
    at ReactDOMComponent._updateDOMChildren (http://localhost:3450/js/compiled/test_out/lib.js:21365:12)
    at ReactDOMComponent.updateComponent (http://localhost:3450/js/compiled/test_out/lib.js:21183:10)
    at ReactDOMComponent.receiveComponent (http://localhost:3450/js/compiled/test_out/lib.js:21141:10)
    at Object.receiveComponent (http://localhost:3450/js/compiled/test_out/lib.js:27349:22)
    at Object.updateChildren (http://localhost:3450/js/compiled/test_out/lib.js:17755:25)
    at ReactDOMComponent._reconcilerUpdateChildren (http://localhost:3450/js/compiled/test_out/lib.js:25982:32)
    at ReactDOMComponent._updateChildren (http://localhost:3450/js/compiled/test_out/lib.js:26086:31)
    at ReactDOMComponent.updateChildren (http://localhost:3450/js/compiled/test_out/lib.js:26073:12)
    at ReactDOMComponent._updateDOMChildren (http://localhost:3450/js/compiled/test_out/lib.js:21365:12)
    at ReactDOMComponent.updateComponent (http://localhost:3450/js/compiled/test_out/lib.js:21183:10)
    at ReactDOMComponent.receiveComponent (http://localhost:3450/js/compiled/test_out/lib.js:21141:10)
    at Object.receiveComponent (http://localhost:3450/js/compiled/test_out/lib.js:27349:22)
    at Object.updateChildren (http://localhost:3450/js/compiled/test_out/lib.js:17755:25)
    at ReactDOMComponent._reconcilerUpdateChildren (http://localhost:3450/js/compiled/test_out/lib.js:25982:32)
    at ReactDOMComponent._updateChildren (http://localhost:3450/js/compiled/test_out/lib.js:26086:31)
    at ReactDOMComponent.updateChildren (http://localhost:3450/js/compiled/test_out/lib.js:26073:12)
    at ReactDOMComponent._updateDOMChildren (http://localhost:3450/js/compiled/test_out/lib.js:21365:12)
    at ReactDOMComponent.updateComponent (http://localhost:3450/js/compiled/test_out/lib.js:21183:10)
    at ReactDOMComponent.receiveComponent (http://localhost:3450/js/compiled/test_out/lib.js:21141:10)
    at Object.receiveComponent (http://localhost:3450/js/compiled/test_out/lib.js:27349:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:3450/js/compiled/test_out/lib.js:20092:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://localhost:3450/js/compiled/test_out/lib.js:20070:10)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:3450/js/compiled/test_out/lib.js:19989:12)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (http://localhost:3450/js/compiled/test_out/lib.js:19897:12)
    at Object.performUpdateIfNecessary (http://localhost:3450/js/compiled/test_out/lib.js:27381:22)
    at runBatchedUpdates (http://localhost:3450/js/compiled/test_out/lib.js:28521:21)
    at ReactReconcileTransaction.perform (http://localhost:3450/js/compiled/test_out/lib.js:30772:20)
    at ReactUpdatesFlushTransaction.perform (http://localhost:3450/js/compiled/test_out/lib.js:30772:20)
    at Object.flushBatchedUpdates (http://localhost:3450/js/compiled/test_out/lib.js:28543:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (http://localhost:3450/js/compiled/test_out/lib.js:30838:25)
    at ReactDefaultBatchingStrategyTransaction.perform (http://localhost:3450/js/compiled/test_out/lib.js:30785:16)
    at Object.batchedUpdates (http://localhost:3450/js/compiled/test_out/lib.js:23778:19)
    at Object.batchedUpdates (http://localhost:3450/js/compiled/test_out/lib.js:28468:20)
    at dispatchEvent (http://localhost:3450/js/compiled/test_out/lib.js:24761:20)
G__54238__delegate  @   core.cljs:65
G__54238    @   core.cljs:61
_customPreview
InjectedScript.RemoteObject
_wrapObject
getProperties
```

**Comment by darwin** [comment]
The problem is in cljs printing subsystem which does not handle javascript (native) symbols gracefully.

See http://dev.clojure.org/jira/browse/CLJS-1631.

**Comment by rauhs** [comment]
FYI: I fixed this for now with a:

```clojure
(extend-protocol IPrintWithWriter
  js/Symbol
  (-pr-writer [sym writer _]
    (-write writer (str "\"" (.toString sym) "\""))))
```

**Comment by darwin** [comment]
@rauhs that solves only part of the problem. You solution works only for `print` family of functions which go through IPrintWithWriter.

If you were to call `str` directly, you would still hit the problem. Complete solution is to replace `cljs.core.str`[1] with a sanitized version.

https://github.com/clojure/clojurescript/blob/cb3e8c295ad5ed1961e7db1d0b19674eb7f71a5c/src/main/cljs/cljs/core.cljs#L2807

**Comment by darwin** [comment]
https://github.com/clojure/clojurescript/commit/c057c92bd20bb4bea61970fb87247582ae2f5423
