### ISSUE TITLE
0.4.1 No such namespace: cljs.stacktrace

### ISSUE THREAD

**Issue by dariooddenino** [binaryage/cljs-devtools#7]
Hi, I wanted to try devtools today, but I get this exception:

```
clojure.lang.ExceptionInfo: No such namespace: cljs.stacktrace, could not locate cljs/stacktrace.cljs or cljs/stacktrace.cljc at line 1 file:/home/dario/.m2/repository/binaryage/devtools/0.4.1/devtools-0.4.1.jar!/devtools/sanity_hints.cljs {:file "file:/home/dario/.m2/repository/binaryage/devtools/0.4.1/devtools-0.4.1.jar!/devtools/sanity_hints.cljs", :line 1, :column 1, :tag :cljs/analysis-error}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at cljs.analyzer$error.invoke(analyzer.clj:379)
	at cljs.analyzer$error.invoke(analyzer.clj:377)
	at cljs.analyzer$analyze_deps.invoke(analyzer.clj:1264)
	at cljs.analyzer$eval1860$fn__1862.invoke(analyzer.clj:1516)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq.invoke(analyzer.clj:1861)
	at cljs.analyzer$analyze$fn__2108.invoke(analyzer.clj:1953)
	at cljs.analyzer$analyze.invoke(analyzer.clj:1946)
	at cljs.analyzer$analyze_file$fn__2159.invoke(analyzer.clj:2190)
	at cljs.analyzer$analyze_file.invoke(analyzer.clj:2185)
	at cljs.analyzer$analyze_deps.invoke(analyzer.clj:1262)
	at cljs.analyzer$eval1860$fn__1862.invoke(analyzer.clj:1516)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq.invoke(analyzer.clj:1861)
	at cljs.analyzer$analyze$fn__2108.invoke(analyzer.clj:1953)
	at cljs.analyzer$analyze.invoke(analyzer.clj:1946)
	at cljs.analyzer$analyze_file$fn__2159.invoke(analyzer.clj:2190)
	at cljs.analyzer$analyze_file.invoke(analyzer.clj:2185)
	at cljs.analyzer$analyze_deps.invoke(analyzer.clj:1262)
	at cljs.analyzer$eval1860$fn__1862.invoke(analyzer.clj:1516)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq.invoke(analyzer.clj:1861)
	at cljs.analyzer$analyze$fn__2108.invoke(analyzer.clj:1953)
	at cljs.analyzer$analyze.invoke(analyzer.clj:1946)
	at cljs.analyzer$analyze_file$fn__2159.invoke(analyzer.clj:2190)
	at cljs.analyzer$analyze_file.invoke(analyzer.clj:2185)
	at figwheel_sidecar.repl$analyze_build.invoke(repl.clj:252)
	at figwheel_sidecar.repl$analyze_builds.invoke(repl.clj:257)
	at figwheel_sidecar.repl$run_autobuilder_helper.invoke(repl.clj:305)
	at figwheel_sidecar.repl$start_autobuild.invoke(repl.clj:376)
	at figwheel_sidecar.repl$run_autobuilder.invoke(repl.clj:535)
	at user$eval17992.invoke(form-init4556655145684270557.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Subprocess failed
```

**Comment by darwin** [comment]
Hmm, I would guess you are trying to include it into a project with ancient ClojureScript version.

The latest ClojureScript "1.7.170" is your best bet. Running `lein deps :tree` might help discovering which of your dependencies is pulling old ClojureScript version in.

**Comment by dariooddenino** [comment]
You guessed right! Somehow I had a super old ClojureScript version in my project.
Thanks!
