### ISSUE TITLE
lein demo throws

### ISSUE THREAD

**Issue by nchevobbe** [binaryage/cljs-devtools#70]
I followed https://github.com/binaryage/cljs-devtools/blob/master/examples/lein/readme.md after cloning the repo and installing `lein` on my machine, but when I run `lein demo`, I'm getting the following error on both OSX and Ubuntu:

```
Figwheel: Cutting some fruit, just a sec ...
Figwheel: Starting server at http://0.0.0.0:8000
Figwheel: Watching build - demo
Figwheel: Cleaning build - demo
Compiling build :demo to "resources/public/.compiled/demo/devtools_sample.js" from ["src/demo" "src/tests"]...
Successfully compiled build :demo to "resources/public/.compiled/demo/devtools_sample.js" in 12.681 seconds.
clojure.lang.ExceptionInfo: Error in component :figwheel-system in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start {:reason :com.stuartsierra.component/component-function-threw-exception, :function #'com.stuartsierra.component/start, :system-key :figwheel-system, :component #figwheel_sidecar.system.FigwheelSystem{:system #object[clojure.lang.Atom 0x29179d87 {:status :ready, :val #<SystemMap>}]}, :system #<SystemMap>}
	at com.stuartsierra.component$try_action.invokeStatic(component.cljc:120)
	at com.stuartsierra.component$try_action.invoke(component.cljc:117)
	at com.stuartsierra.component$update_system$fn__18881.invoke(component.cljc:140)
	at clojure.lang.ArraySeq.reduce(ArraySeq.java:111)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at com.stuartsierra.component$update_system.invokeStatic(component.cljc:136)
	at com.stuartsierra.component$update_system.doInvoke(component.cljc:130)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at com.stuartsierra.component$start_system.invokeStatic(component.cljc:164)
	at com.stuartsierra.component$start_system.invoke(component.cljc:156)
	at com.stuartsierra.component$start_system.invokeStatic(component.cljc:162)
	at com.stuartsierra.component$start_system.invoke(component.cljc:156)
	at com.stuartsierra.component.SystemMap.start(component.cljc:179)
	at figwheel_sidecar.system$start_figwheel_system$fn__20652.invoke(system.clj:673)
	at figwheel_sidecar.system$dispatch_system_component_errors.invokeStatic(system.clj:659)
	at figwheel_sidecar.system$dispatch_system_component_errors.invoke(system.clj:657)
	at figwheel_sidecar.system$start_figwheel_system.invokeStatic(system.clj:673)
	at figwheel_sidecar.system$start_figwheel_system.invoke(system.clj:671)
	at figwheel_sidecar.system$start_figwheel_BANG__STAR_.invokeStatic(system.clj:708)
	at figwheel_sidecar.system$start_figwheel_BANG__STAR_.invoke(system.clj:694)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at figwheel_sidecar.system$start_figwheel_BANG_.invokeStatic(system.clj:752)
	at figwheel_sidecar.system$start_figwheel_BANG_.doInvoke(system.clj:710)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at figwheel_sidecar.repl_api$start_figwheel_from_lein.invokeStatic(repl_api.clj:151)
	at figwheel_sidecar.repl_api$start_figwheel_from_lein.invoke(repl_api.clj:147)
	at figwheel_sidecar.repl_api$launch_from_lein.invokeStatic(repl_api.clj:224)
	at figwheel_sidecar.repl_api$launch_from_lein.invoke(repl_api.clj:216)
	at user$eval20729.invokeStatic(form-init3858462508830366274.clj:1)
	at user$eval20729.invoke(form-init3858462508830366274.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7177)
	at clojure.lang.Compiler.eval(Compiler.java:7167)
	at clojure.lang.Compiler.load(Compiler.java:7636)
	at clojure.lang.Compiler.loadFile(Compiler.java:7574)
	at clojure.main$load_script.invokeStatic(main.clj:475)
	at clojure.main$init_opt.invokeStatic(main.clj:477)
	at clojure.main$init_opt.invoke(main.clj:477)
	at clojure.main$initialize.invokeStatic(main.clj:508)
	at clojure.main$null_opt.invokeStatic(main.clj:542)
	at clojure.main$null_opt.invoke(main.clj:539)
	at clojure.main$main.invokeStatic(main.clj:664)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
Caused by: clojure.lang.ExceptionInfo: Error in component autobuild-demo in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start {:reason :com.stuartsierra.component/component-function-threw-exception, :function #'com.stuartsierra.component/start, :system-key "autobuild-demo", :component #figwheel_sidecar.components.cljs_autobuild.CLJSAutobuild{:build-config {:source-paths ["src/demo" "src/tests"], :figwheel {:build-id "demo"}, :id "demo", :watch-paths ["src/demo" "src/tests"], :compile-paths ["src/demo" "src/tests"], :build-options {:output-to "resources/public/.compiled/demo/devtools_sample.js", :output-dir "resources/public/.compiled/demo", :asset-path ".compiled/demo", :main devtools-sample.boot, :preloads [devtools.preload], :optimizations :none, :source-map true, :source-map-timestamp true}, :compiler-env #object[clojure.lang.Atom 0x26a3f0ab {:status :ready, :val #CompilerEnv{}}]}, :figwheel-server #figwheel_sidecar.components.figwheel_server.FigwheelServer{:connection-count #object[clojure.lang.Atom 0x1f99469b {:status :ready, :val {}}], :browser-callbacks #object[clojure.lang.Atom 0xa770b4a {:status :ready, :val {}}], :validate-config false, :ring-handler nil, :file-change-atom #object[clojure.lang.Atom 0x4453299e {:status :ready, :val ()}], :compile-wait-time 10, :builds {"demo" {:source-paths ["src/demo" "src/tests"], :figwheel {:build-id "demo"}, :id "demo", :watch-paths ["src/demo" "src/tests"], :compile-paths ["src/demo" "src/tests"], :build-options {:output-to "resources/public/.compiled/demo/devtools_sample.js", :output-dir "resources/public/.compiled/demo", :asset-path ".compiled/demo", :main devtools-sample.boot, :preloads [devtools.preload], :optimizations :none, :source-map true, :source-map-timestamp true}, :compiler-env #object[clojure.lang.Atom 0x26a3f0ab {:status :ready, :val #CompilerEnv{}}]}}, :server-logfile ".figwheel/server.log", :server-port 8000, :resolved-ring-handler nil, :server-ip "0.0.0.0", :cljs-build-fn #object[figwheel_sidecar.components.cljs_autobuild$color_output$fn__20323 0x7dccaf17 "figwheel_sidecar.components.cljs_autobuild$color_output$fn__20323@7dccaf17"], :http-server #object[clojure.lang.AFunction$1 0x283483ab "clojure.lang.AFunction$1@283483ab"], :open-file-command nil, :unique-id "/Users/nchevobbe/Projects/cljs-devtools/examples/lein", :log-writer #object[java.io.BufferedWriter 0x1a2be0bc "java.io.BufferedWriter@1a2be0bc"], :file-md5-atom #object[clojure.lang.Atom 0x47e935be {:status :ready, :val {}}], :http-server-root "public"}}, :system #<SystemMap>}
	at com.stuartsierra.component$try_action.invokeStatic(component.cljc:120)
	at com.stuartsierra.component$try_action.invoke(component.cljc:117)
	at com.stuartsierra.component$update_system$fn__18881.invoke(component.cljc:140)
	at clojure.lang.ArraySeq.reduce(ArraySeq.java:116)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at com.stuartsierra.component$update_system.invokeStatic(component.cljc:136)
	at com.stuartsierra.component$update_system.doInvoke(component.cljc:130)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at com.stuartsierra.component$start_system.invokeStatic(component.cljc:164)
	at com.stuartsierra.component$start_system.invoke(component.cljc:156)
	at com.stuartsierra.component$start_system.invokeStatic(component.cljc:162)
	at com.stuartsierra.component$start_system.invoke(component.cljc:156)
	at com.stuartsierra.component.SystemMap.start(component.cljc:179)
	at com.stuartsierra.component$eval18814$fn__18815$G__18804__18817.invoke(component.cljc:5)
	at com.stuartsierra.component$eval18814$fn__18815$G__18803__18820.invoke(component.cljc:5)
	at clojure.lang.Atom.swap(Atom.java:37)
	at clojure.core$swap_BANG_.invokeStatic(core.clj:2352)
	at clojure.core$swap_BANG_.invoke(core.clj:2345)
	at figwheel_sidecar.system.FigwheelSystem.start(system.clj:124)
	at com.stuartsierra.component$eval18814$fn__18815$G__18804__18817.invoke(component.cljc:5)
	at com.stuartsierra.component$eval18814$fn__18815$G__18803__18820.invoke(component.cljc:5)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at com.stuartsierra.component$try_action.invokeStatic(component.cljc:118)
	... 48 more
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/nf/2ssdy4r10bv3m1ng1b282nqh0000gn/T/jna12061916177744929205.tmp
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2408)
	at java.base/java.lang.Runtime.load0(Runtime.java:785)
	at java.base/java.lang.System.load(System.java:2009)
	at com.sun.jna.Native.loadNativeLibraryFromJar(Native.java:744)
	at com.sun.jna.Native.loadNativeLibrary(Native.java:678)
	at com.sun.jna.Native.<clinit>(Native.java:106)
	at com.barbarysoftware.jna.CarbonAPI.<clinit>(CarbonAPI.java:6)
	at com.barbarysoftware.jna.CFStringRef.toCFString(CFStringRef.java:10)
	at com.barbarysoftware.watchservice.MacOSXListeningWatchService.register(MacOSXListeningWatchService.java:30)
	at com.barbarysoftware.watchservice.WatchableFile.register(WatchableFile.java:30)
	at com.barbarysoftware.watchservice.WatchableFile.register(WatchableFile.java:39)
	at hawk.watcher$fn__133.invokeStatic(watcher.clj:102)
	at hawk.watcher$fn__133.invoke(watcher.clj:99)
	at hawk.watcher$fn__38$G__29__47.invoke(watcher.clj:24)
	at hawk.core$watch_BANG_.invokeStatic(core.clj:83)
	at hawk.core$watch_BANG_.doInvoke(core.clj:59)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at figwheel_sidecar.watching$watch_BANG_.invokeStatic(watching.clj:75)
	at figwheel_sidecar.watching$watch_BANG_.invoke(watching.clj:41)
	at figwheel_sidecar.components.cljs_autobuild.CLJSAutobuild.start(cljs_autobuild.clj:276)
	at com.stuartsierra.component$eval18814$fn__18815$G__18804__18817.invoke(component.cljc:5)
	at com.stuartsierra.component$eval18814$fn__18815$G__18803__18820.invoke(component.cljc:5)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:660)
	at com.stuartsierra.component$try_action.invokeStatic(component.cljc:118)
	... 75 more
```

We're currently wrapping up the work to add custom formatters in Firefox and I'd like to see how we compare with Chrome on a project using complex formatters

**Comment by darwin** [comment]
I'm sorry I was unable to reproduce it here on my macOS machine with a clean checkout.

From the stack trace it looks like it is has trouble to use some native filesystem watcher services. Could be java releated. Mine:

```
❯ java -version
openjdk version "19" 2022-09-20
OpenJDK Runtime Environment Homebrew (build 19)
OpenJDK 64-Bit Server VM Homebrew (build 19, mixed mode, sharing)
```

**Comment by SebastianZ** [comment]
For what it's worth, I _could_ get it to run on Windows 11.

Unfortunately, the script currently checks whether the the browser being Chrome which lets the formatters not work in Firefox. (A user agent switcher can circumvent that, though.)

Sebastian

**Comment by nchevobbe** [comment]
my bad, I got it running on Ubuntu.
Sorry for the noise
